### ISSUE TITLE
Cannot import reboundx in Python: 'cannot open shared object file'

### ISSUE THREAD

**Issue by TimDPearce** [dtamayo/reboundx#141]
I installed rebound and reboundx for Python on my Linux computer using pip (Ubuntu 22.04.5 LTS, 64-bit, GNOME version 42.9). I ran one command at a time, i.e.

pip install rebound
pip install reboundx

When I import reboundx in Python I get an error. My Python code is:

import rebound
import reboundx

The error I get on my work computer is:

    import reboundx
  File "/home/physics/phscrr/.local/lib/python3.9/site-packages/reboundx/__init__.py", line 14, in <module>
    clibreboundx = cdll.LoadLibrary(pymodulespath + '/../libreboundx' + suffix)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: librebound.cpython-39-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory

I have found that I can get around this error by instead installing reboundx using sudo privileges, i.e. 

sudo pip install reboundx

If I do this then reboundx imports fine. However, this isn't a workable solution for me because I also need to use the code on my work's computing system, where I do not have sudo rights. The same import issue persists on the the work computers.

The package versions on my computer are:

Python 3.10.12
rebound==4.4.5
reboundx==4.4.0

On the work computers the versions are:

Python 3.9.21
rebound==4.1.1
reboundx==4.4.0

Previous workarounds for this (issues 26 and 39) do not work for me.

Any help would be much appreciated! I'm happy to give more information if needed.

Tim Pearce

**Comment by TimDPearce** [comment]
Hi Hanno, I wasn't using a virtual environment, but I've just tried with venv and unfortunately the problem persists

**Comment by dtamayo** [comment]
Thanks for the testing! Is it possible to use the latest version of REBOUND on the work computers? What version of REBOUND were you using with the virtual environment? Or do you need an older version of REBOUND?

**Comment by TimDPearce** [comment]
Hi Dan, in the virtual environment on the work computers I used the following versions:

rebound==4.4.5
reboundx==4.4.0

**Comment by dtamayo** [comment]
This is helpful! Looking into it

**Comment by dtamayo** [comment]
I can't reproduce this on my own Ubuntu machines, which makes it hard to debug. When you run things in a virtual environment with the latest REBOUND and REBOUNDx, do you get the same error as above?

File "/home/physics/phscrr/.local/lib/python3.9/site-packages/reboundx/init.py", line 14, in
clibreboundx = cdll.LoadLibrary(pymodulespath + '/../libreboundx' + suffix)
File "/usr/lib64/python3.9/ctypes/init.py", line 452, in LoadLibrary
return self._dlltype(name)
File "/usr/lib64/python3.9/ctypes/init.py", line 374, in init
self._handle = _dlopen(self._name, mode)
OSError: librebound.cpython-39-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory

If so, could you run these commands on the command prompt and let me know what they say? (replacing the paths if they're different, taking the first line in the error message)

ls /home/physics/phscrr/.local/lib/python3.9/site-packages/reboundx/libreb*
ls /home/physics/phscrr/.local/lib/python3.9/site-packages/libreb*

**Comment by TimDPearce** [comment]
Hi, yes if I run on my work computer in a virtual environment ('myenv') with the latest REBOUND and REBOUNDx, I get the same error. Copied from the terminal:


Traceback (most recent call last):
  File "/storage/astro2/phscrr/science/reboundxTest/importErrorReboundxTest.py", line 2, in <module>
    import reboundx
  File "/storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/reboundx/__init__.py", line 14, in <module>
    clibreboundx = cdll.LoadLibrary(pymodulespath + '/../libreboundx' + suffix)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: librebound.cpython-39-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory


Typing in your commands with different paths, in response to 

ls /storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/reboundx/libreb*

I get nothing (there are no files names starting libreb in that directory).


For the second, 

ls /storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/libreb*

I find two files:

/storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/librebound.cpython-39-x86_64-linux-gnu.so

/storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/libreboundx.cpython-39-x86_64-linux-gnu.so

**Comment by hannorein** [comment]
Just to make absolutely sure there's no confusion with how virtual environments work, these are the commands to start from scratch:

```
mkdir test
cd test 
deactivate    # just in case a venv is already active
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install rebound reboundx
python 
...
```

**Comment by TimDPearce** [comment]
Hi Hanno, still the same error I'm afraid, even copying your commands line by line. I also tried your commands but separating out 'pip install rebound reboundx' to 'pip install rebound' then 'pip install reboundx', but still no change

**Comment by ben-cassese** [comment]
Hi all! Just chiming in with a related issue: I get the same error when trying to install reboundx using uv as my package/environment manager. Although I can run the virtual environment creation suggested by Hanno without any errors, creating a virtual environment via uv leads to problems:

```console
uv init --lib reboundx_demo --python 3.13
cd reboundx_demo
uv add rebound
uv add reboundx
uv run python /home/bc838/palmer_scratch/test.py
```

Here `test.py` is just
```python
import rebound
print("rebound imported")
import reboundx
print("reboundx imported")
```

This produces the following error (and unrelated syntax warning for the Trace citation, which is missing an extra backslash in front of /mnras [here](https://github.com/hannorein/rebound/blob/c653292a132644a10e9494e5db90a90342065d32/rebound/citations.py#L171) @tigerchenlu98):

```console
/vast/palmer/scratch/rice_malena/bc838/reboundx_demo/.venv/lib/python3.13/site-packages/rebound/citations.py:168: SyntaxWarning: invalid escape sequence '\m'
  bib += """@ARTICLE{reboundtrace,
rebound imported
Traceback (most recent call last):
  File "/home/bc838/palmer_scratch/test.py", line 3, in <module>
    import reboundx
  File "/vast/palmer/scratch/rice_malena/bc838/reboundx_demo/.venv/lib/python3.13/site-packages/reboundx/__init__.py", line 14, in <module>
    clibreboundx = cdll.LoadLibrary(pymodulespath + '/../libreboundx' + suffix)
  File "/home/bc838/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/lib/python3.13/ctypes/__init__.py", line 471, in LoadLibrary
    return self._dlltype(name)
           ~~~~~~~~~~~~~^^^^^^
  File "/home/bc838/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/lib/python3.13/ctypes/__init__.py", line 390, in __init__
    self._handle = _dlopen(self._name, mode)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
OSError: librebound.cpython-313-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

Same as noted in #39, this error doesn't appear when running the exact same code on a macos system. This isn't blocking anything for me atm, just wanted to provide another example of where the error appears. Thanks for looking into it!

**Comment by hannorein** [comment]
I've fixed the backslash error in version 4.4.6. Thanks for pointing that out!

I've never used uv. So I don't have any advice... But I'm a bit suspicious of whatever trickery it uses to get a 10-100x speedup.

**Comment by dtamayo** [comment]
Hi,

Apologies...I got distracted by the holidays and this fell off my radar. Can you try installing from this new branch with this command?

pip install git+https://github.com/dtamayo/reboundx.git@install

**Comment by hannorein** [comment]
I can reproduce the issue with uv on linux (it works on Mac). Here is a workaround turning off build-isolation that works for me:

```bash
uv pip uninstall reboundx
uv cache clean
uv pip install setuptools
uv pip install reboundx --no-build-isolation
```

Does that help in your case too?

**Comment by hannorein** [comment]
@dtamayo if this work for others, we should add 

```
[tool.uv]
no-build-isolation = true
```

to REBOUNDx's `pyproject.toml`.

**Comment by ben-cassese** [comment]
The workaround works for me! One thing I'll note is that removing only reboundx from the uv cache via `uv cache clean reboundx` also worked and is probably preferable so that people can keep the rest of their uv cache intact.

I also briefly tried the usual uv workflow of `uv add reboundx` with a fork of reboundx with the modified pyproject.toml, but unfortunately that runs into the same problem. For some reason it only seems to work through the `uv pip` interface, not `uv add`. That's not disastrous but is kind of a bummer since `uv pip install` adds to a uv project's virtual environment but not its uv.lock file or pyproject.toml dependencies, so users can't recreate the exact environment through uv sync. That's definitely not a high priority issue though, so the workaround is good for now!

**Comment by hannorein** [comment]
Did you run `uv add` with the `--no-build-isolation` flag?

**Comment by ben-cassese** [comment]
Looks like when the --no-build-isolation was just in the pyproject.toml it didn't work, but if I run `uv add reboundx --no-build-isolation` it does, but only after also adding other dependencies. This sequence works when setting up a project:

```console
uv init --lib reboundx_demo --python 3.13
cd reboundx_demo
uv add rebound
uv add setuptools hatchling editables
uv add reboundx --no-build-isolation
```

But, if I then pretend I've distributed my project to a new user by clearing my uv cache and running `uv sync` (or `uv venv`, or `uv run python`, etc), I run into the original error again.

**Comment by hannorein** [comment]
This sequence makes sense. You need to have REBOUND installed before REBOUNDx can get compiled. And REBOUNDx can't be built in isolation because it needs to have access to the REBOUND shared library.

It might well be that I'm missing something but I don't see a way around this for as long as REBOUND and REBOUNDx are both C libraries that need to talk to each other (they need to do that in C, not via a python wrapper, because of speed),

**Comment by dtamayo** [comment]
Thanks @hannorein and @ben-cassese!

@TimDPearce could you let me know if installing from the new branch with the command above works for you?

**Comment by TimDPearce** [comment]
Hi Hanno, do you mean using the command

pip install git+https://github.com/dtamayo/reboundx.git@install --no-build-isolation

? If so, then this produces an error on installation:

creating '/tmp/pip-modern-metadata-vokr90m6/reboundx.dist-info'
error: invalid command 'bdist_wheel'

**Comment by dtamayo** [comment]
It's strange to me from your messages above that it seems like the shared libraries are being built fine, it just can't load them. So maybe it's a path issue?

Could you run the regular pip install reboundx in a new virtualenvironment, and look through the error log.  There should be a line like this that points to where it's running reboundx's __init__.py file:

File "/storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/reboundx/init.py", line 14, in

Could you find it, cd into that reboundx directory, i.e., in the above case: 

cd /storage/astro2/phscrr/science/reboundxTest/myenv/lib64/python3.9/site-packages/reboundx/

and make a new file called print.py in that directory with the following code (which is what REBOUNDx is using to figure out the path to the shared libraries):

```
import` os
import subprocess
pymodulepath = os.path.dirname(os.path.abspath(__file__))
pymodulepath = os.path.abspath(os.path.join(pymodulepath, os.pardir))
print(pymodulepath)
subprocess.run(['ls {0}/librebound*'.format(pymodulepath)], shell=True)
```

then run

python print.py?

**Comment by TimDPearce** [comment]
Hi Dan, this is what I get (after I remove the apostrophe on the first line of print.py):

/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages
/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/librebound.cpython-39-x86_64-linux-gnu.so
/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/libreboundx.cpython-39-x86_64-linux-gnu.so

**Comment by dtamayo** [comment]
Hi Tim,

Hm...could you add these lines to print.py and run it to see if it gives the same error?

```
from ctypes import *
clibrebound = cdll.LoadLibrary('/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/librebound.cpython-39-x86_64-linux-gnu.so')
```

Also, when you get the original errors, are you running import reboundx on the command line with the python interpreter, in a jupyter notebook, or something else?

**Comment by dtamayo** [comment]
Could you also run this on the command line

```
readelf -d /storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/libreboundx.cpython-39-x86_64-linux-gnu.so
```

and then instead of installing with the pip install git+... command, use

```
pip install reboundx --no-build-isolation
```

**Comment by TimDPearce** [comment]
Hi Dan,

As you predicted, I don't get an error from adding the following to print.py:

```
from ctypes import *
clibrebound = cdll.LoadLibrary('/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/librebound.cpython-39-x86_64-linux-gnu.so')
```

Typing 

`ldd /storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/libreboundx.cpython-39-x86_64-linux-gnu.so
`

into the command line printed the following:

```
linux-vdso.so.1 (0x00007ffe4a5ea000)
librebound.cpython-39-x86_64-linux-gnu.so => not found
libc.so.6 => /lib64/libc.so.6 (0x00007fce0aa00000)
/lib64/ld-linux-x86-64.so.2 (0x00007fce0ad3d000)
```

The original error comes up regardless of how I import reboundx; either using the Python command-line interpreter, or executing a .py file, and irrespective of whether I'm using a virtual environment or not.

Typing

`readelf -d /storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/libreboundx.cpython-39-x86_64-linux-gnu.so
`

prints the following:

```
Dynamic section at offset 0x20930 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [librebound.cpython-39-x86_64-linux-gnu.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [.:/tmp/pip-build-env-rraykhmy/overlay/lib64/python3.9/site-packages/rebound/../:/usr/lib64/python3.9/site-packages/]
 0x000000000000000c (INIT)               0x4000
 0x000000000000000d (FINI)               0x1a458
 0x0000000000000019 (INIT_ARRAY)         0x21918
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x21920
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2f0
 0x0000000000000005 (STRTAB)             0x1790
 0x0000000000000006 (SYMTAB)             0x6e0
 0x000000000000000a (STRSZ)              3873 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x21b30
 0x0000000000000002 (PLTRELSZ)           2640 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x2ce0
 0x0000000000000007 (RELA)               0x2878
 0x0000000000000008 (RELASZ)             1128 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x2818
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x26b2
 0x000000006ffffff9 (RELACOUNT)          6
 0x0000000000000000 (NULL)               0x0
```

However, then running

`
pip install reboundx --no-build-isolation
`

and trying to import reboundx still yields the original error.

**Comment by dtamayo** [comment]
OK, well at least I think that narrows down the problem. The ldd command should have librebound.cpython...so pointing with the arrow to where it is, but it's not found. It does seem like there's something funny with how things are set up on this server, where perhaps if you took this info to a sysadmin they'd be able to help.

From trying to google around a bit, if you're getting warnings about old versions of pip, you might try upgrading it first

pip install --upgrade pip

and if you're not doing it, it might be worth quickly trying installing rebound and reboundx separately when using --no-build-isolation

pip install rebound
pip install reboundx --no-build-isolation

Finally, this is not a great solution, but you could try hardcoding the path into your library search path, e.g.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/

or whatever path you're currently using. If that works, you could add it into your .bashrc file

**Comment by TimDPearce** [comment]
Hi Dan,

Thanks a lot, the line 

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/storage/astro2/phscrr/science/myWork/reboundxTest/test/venv/lib/python3.9/site-packages/`

makes reboundx work on the server for me! I can use it in this form. I still don't understand why I had the same problem on my laptop, where using 

`sudo pip install reboundx`

fixed it for me, but either way I have solutions for both machines now.

Thanks a lot Dan and Hanno for all your help!

Tim

**Comment by dtamayo** [comment]
Thanks for all the testing Tim. Not an ideal solution, but I'm glad it provides a workaround and I will try to look into it more. 

Even though they don't solve this problem, I've pushed some cleanups and improvements (including @hannorein suggestion for better supporting uv).

Will close this for now. If others run into the same issue, please reopen and let us know!
